### ISSUE TITLE
Missing #include <algorithm>

### ISSUE THREAD

**Issue by robbr48** [peterNordin/IndexingCSVParser#1]
Newer versions of Visual Studio compilers requires this include for using e.g. `min()` and `max()`. As I understand it, this has always been a requirement, but older versions of visual studio and gcc are less strict for some reason.

See Hopsan/hopsan#1956.

**Comment by peterNordin** [comment]
Fixed
Also added github actions CI for Ubuntu, macOS and MSVC 2019
